services:
  agent:
    build:
      context: .
      dockerfile: agent.Dockerfile
    container_name: demo_agent
    depends_on:
      ollama:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL=${OLLAMA_MODEL}
      - REDIS_HOST=redis
    command: python -u agent.py
    networks:
      - agent-net

  ollama:
    build:
      context: .
      dockerfile: ollama.Dockerfile
    container_name: demo_ollama
    ports:
      - "11434:11434"
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 1s
      timeout: 10s
      retries: 15
    networks:
      - agent-net
    volumes:
      - ollama_data:/root/.ollama

  redis:
    image: "redis:alpine"
    container_name: demo_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - agent-net

networks:
  agent-net:
    driver: bridge

volumes:
  ollama_data: